name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le pipeline à chaque push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Connecter Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 3. Passer au répertoire 'sav_ssi' et construire l'image Docker
      - name: Build Docker Image
        working-directory: sav_ssi  # Répertoire relatif où ton Dockerfile est situé
        run: |
          echo "Navigating to directory: $(pwd)"
          docker build -t mamadoujuniorsy/sav_ssi:latest .

      # 4. Push l'image construite sur Docker Hub
      - name: Push Docker Image
        run: docker push mamadoujuniorsy/sav_ssi:latest
