name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le pipeline à chaque push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Lister les fichiers dans le répertoire racine
      - name: List files in the root directory after checkout
        run: ls -la

      # 3. Lister les fichiers dans le répertoire 'sav_ssi'
      - name: List files in the sav_ssi directory
        run: ls -la sav_ssi

      # 4. Vérifier la version de Docker et Git
      - name: Check Docker version
        run: docker --version

      - name: Check Git version
        run: git --version

      # 5. Vérifier le répertoire actuel et les fichiers
      - name: Print current working directory
        run: pwd

      - name: Print files in current directory
        run: ls -la

      # 6. Connecter Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 7. Construire l'image Docker à partir du répertoire 'sav_ssi'
      - name: Build Docker Image
        run: |
          docker build -t mamadoujuniorsy/sav_ssi:latest ./sav_ssi

      # 8. Push l'image construite sur Docker Hub
      - name: Push Docker Image
        run: docker push mamadoujuniorsy/sav_ssi:latest
